
version: '3.9'

services:
  web:
    build: ./django
    container_name: django-app
    env_file: .env
    volumes:
      - ./django:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy 

  db:
    image: postgres:latest  
    container_name: postgres
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/script.sh:/usr/local/bin/script.sh 
    command: ["bash", "/usr/local/bin/script.sh"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx
    env_file: .env
    ports:
      - "4443:443" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/ssl
    depends_on:
      - web

volumes:
  db_data:
