version: '3.9'

services:
  web:
    build: ./django
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest  
    container_name: postgres
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    volumes:
      - db_data:/var/lib/postgresql/data


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4443:443" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/ssl
    depends_on:
      - web

volumes:
  db_data:
