version: '3.9'

services:
  web:
    build: ./django
    container_name: django-app
    env_file: .env
    volumes:
      - ./django:/usr/src/app
      - static_volume:/usr/src/app/staticfiles  # Partage le volume avec Nginx
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - webnet

  db:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/script.sh:/usr/local/bin/script.sh
    command: ["bash", "/usr/local/bin/script.sh"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - webnet

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_HOST=redis
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx
    env_file: .env
    ports:
      - "4443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/ssl
      - static_volume:/usr/src/app/staticfiles  # Monte le volume partagé
    depends_on:
      - web
    networks:
      - webnet

volumes:
  db_data:
  static_volume:

networks:
  webnet:
